"""add guest id to user table

Revision ID: 5b919781deb4
Revises: add_video_gen_count_20251008
Create Date: 2025-10-17 19:42:30.353685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b919781deb4'
down_revision = 'add_video_gen_count_20251008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'generating'"))

    with op.batch_alter_table('slops', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'reports', ['report_id'], ['id'])
        batch_op.create_foreign_key(None, 'suggestions', ['suggestion_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_guest_id'), ['guest_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_guest_id'))
        batch_op.drop_column('guest_id')

    with op.batch_alter_table('slops', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('memes', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'generating'"))

    # ### end Alembic commands ###
