"""plan id constraint chaange

Revision ID: cffce3041414
Revises: 54d8efab46cd
Create Date: 2025-10-07 01:12:39.498287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cffce3041414'
down_revision = '54d8efab46cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_subscriptions_ibfk_1'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('user_subscriptions_ibfk_1'), 'subscription_plans', ['plan_id'], ['id'])

    # ### end Alembic commands ###
